// The Events family of the fixture backend — every `/events` route, public and admin, in one file.
//
// ---- WHY IT IS ONE FILE, AND WHY IT MOVED HERE -------------------------------------------------
//
// The public proposal routes and the admin reads used to live in `api-server.js`, on opposite sides
// of the auth wall and ninety lines apart. That was survivable while the guest surface had no gate:
// there was nothing the two halves had to agree about. `F-EV-ACCEPT-UNGATED` closed that — the public
// accept and decline now refuse for a store without `Events.Core` — and the gate needs the one thing
// only both halves together know: which store a guest token belongs to.
//
// A gate with two enforcement points is a gate with one of them missing, eventually. So the whole
// module family is here, the way `margin.js`, `meals.js` and `training.js` already are, and the
// token -> store -> flag resolution happens once. Route-for-route with `EventsController`,
// `EventsSettlementController` and the two guest controllers, so the two can be diffed by eye.
//
// ---- WHAT IT MODELS ----------------------------------------------------------------------------
//
// TWO WORLDS, on purpose:
//
//   THE STANDING WORLD is `world.ADMIN_EVENT_*` and `world.PROPOSALS` — one Confirmed event and two
//   sent proposal versions, read-only, seeded so the run-sheet and guest-proposal journeys have
//   something to open. Served exactly as it was before this file existed.
//
//   THE LIVING WORLD is `state.events`, which starts EMPTY and is built by the journey that walks it:
//   a public enquiry creates an event, the venue drafts and sends a proposal version, the guest
//   accepts it, and the settlement tail closes it. Nothing here is seeded, because a walk whose whole
//   subject is "these steps connect" cannot be evidence if the connections were placed by hand.
//
// WHAT IT DOES NOT MODEL, and refuses rather than invents: the deposit money path (T7/T9/T10 —
// issuing, paying and cancelling a deposit), amendments (T17), mark-lost, cancel, pos-links,
// availability, notification requeue and run-sheet generation. Each is a contract this fixture does
// not hold, and a fixture that quietly accepted a write it does not model would let a journey walk a
// step no server performed.
//
// ---- THE STORE GATE ----------------------------------------------------------------------------
//
// `Events.Core` is deny-closed and gates BOTH sides, in two different dialects, and the difference is
// the backend's rather than a choice made here:
//
//   admin   404 `EVENTS_DISABLED`. The venue is invisible: no pipeline, no event, no run sheet.
//   public  404 `EVENTS_PROPOSAL_NOT_FOUND` — the SAME refusal an unknown token gets
//           (`EventsProposalService.GuardStoreEnabledAsync`). An anonymous caller must not be able to
//           tell "this venue has not opted in" from "no such link", because that answer is a roster
//           of which venues did.
//
// AND ONE WRITE IS DELIBERATELY UNGATED: `POST /events/inquiries`. That is `F-EV-INQUIRY-UNGATED`,
// open as a product question rather than a defect — the enquiry form is plausibly how a venue
// discovers the module at all, so whether the answer is "refuse the write" or "the form should not be
// reachable for an un-opted store" is not this fixture's call. It is modelled as it behaves:
// `EventsInquiryService` takes no `IEventsModuleGate` at all, so the write succeeds for a store that
// cannot then see the result. A journey walking it can therefore SHOW that consequence rather than
// assert it.

const crypto = require('crypto');
const world = require('./world');

const CORE_FLAG = world.EVENTS_CORE_FLAG;
const SETTLEMENT_FLAG = world.EVENTS_SETTLEMENT_FLAG;

/** `EventsProposalLineKind`. The server `Enum.TryParse`s the name and refuses anything else. */
const PROPOSAL_LINE_KINDS = ['Package', 'MenuItem', 'AddOn', 'RoomFee', 'Custom'];

/**
 * The settlement line kinds a CALLER may author.
 *
 * `DepositApplied` and `PosCheck` are generated by close and by pos-links and `AddLineAsync` refuses
 * either from a caller; `Refund` is in the enum and is refused as well. Modelled because the page
 * offers exactly two, and a fixture that accepted four would let a third appear unnoticed.
 */
const AUTHORABLE_SETTLEMENT_LINE_KINDS = ['Invoice', 'Adjustment'];

function fresh () {
  return {
    // The living world. Empty on purpose — see the header.
    events: [],
    seq: 0
  };
}

const nowUtc = () => new Date().toISOString().slice(0, 19) + 'Z';

/** A stable short digest, standing in for the GUIDs and row versions the server mints. */
function digest (text) {
  return crypto.createHash('sha256').update(String(text)).digest('hex');
}

/** A GUID-shaped id, because `publicId` is a Guid on the wire and a page prints it as a reference. */
function guidFrom (text) {
  const hex = digest(text);
  return [hex.slice(0, 8), hex.slice(8, 12), hex.slice(12, 16), hex.slice(16, 20), hex.slice(20, 32)].join('-');
}

// ---- refusals ----------------------------------------------------------------------------------

/**
 * The single refusal every Events ADMIN gate collapses to.
 *
 * 404 and not 403, and the same 404 for all three `Events.*` flags: `EventsProblemException.Disabled()`
 * carries `EVENTS_DISABLED` and NOTHING that says which switch is down, so a client cannot tell "the
 * module is off for this store" from "the settlement flag is off" from "no such store".
 */
function disabled (ctx) {
  ctx.problem(404, 'EVENTS_DISABLED', 'Events is not enabled for this store.');
  return true;
}

/**
 * The single refusal the PUBLIC proposal routes collapse to — for an unknown token, for a version
 * that was never sent, AND for a token whose venue does not have `Events.Core`.
 *
 * That last one is `F-EV-ACCEPT-UNGATED`'s fix, and reusing this code is deliberate: the guest page
 * already renders it, so there is no unhandled failure where a refusal belongs.
 */
function proposalNotFound (ctx) {
  ctx.problem(404, 'EVENTS_PROPOSAL_NOT_FOUND', 'No sent version matches this link.');
  return true;
}

function validation (ctx, detail) {
  ctx.problem(400, 'EVENTS_VALIDATION', detail);
  return true;
}

/** 400 `EVENTS_PROPOSAL_INVALID` — the send preflight, which is about the VERSION, not the event. */
function proposalInvalid (ctx, detail) {
  ctx.problem(400, 'EVENTS_PROPOSAL_INVALID', detail);
  return true;
}

/**
 * A lifecycle action asked for from a status that does not permit it.
 *
 * It carries `currentStatus` and `permittedActions`, which are the two extensions
 * `EventsProblemException.State` adds and the reason a refused caller never has to guess.
 */
function stateRefusal (ctx, currentStatus, permittedActions) {
  ctx.problem(409, 'EVENTS_STATE', 'That action is not available from ' + currentStatus + '.',
    { currentStatus, permittedActions: permittedActions || [] });
  return true;
}

function settlementState (ctx, detail) {
  ctx.problem(409, 'EVENTS_SETTLEMENT_STATE', detail);
  return true;
}

function notFound (ctx) {
  ctx.problem(404, 'EVENTS_NOT_FOUND', 'No event with that id in this fixture.');
  return true;
}

// ---- the living world --------------------------------------------------------------------------

function slice (ctx) {
  return ctx.state.events;
}

function findEvent (events, storeId, eventId) {
  return events.events.find(
    row => String(row.id) === String(eventId) && String(row.storeId) === String(storeId)) || null;
}

/** Which event and version a public token belongs to, across BOTH worlds. */
function findByToken (ctx, token) {
  for (const event of slice(ctx).events) {
    const version = event.versions.find(v => v.publicToken === token);
    if (version) { return { event, version, standing: null }; }
  }
  // The standing world's two tokens. They belong to `world.GUEST_VENUE_STORE_ID` — a venue that HAS
  // the module, which is what a SENT proposal implies. See that constant's comment.
  const standing = ctx.state.proposals[token];
  if (standing) {
    return { event: { storeId: world.GUEST_VENUE_STORE_ID }, version: null, standing };
  }
  return null;
}

/**
 * One append-only lifecycle row, and the event's status moved with it.
 *
 * `actorKind` is `EventsActorKind` — `Admin`, `Guest` or `System`, and which one is recorded is the
 * point of the column: a guest's acceptance and the system's zero-deposit promotion are two different
 * facts about who caused a booking to be confirmed.
 */
function transition (event, action, toStatus, actorKind, reasonCode) {
  event.transitions.push({
    createdAtUtc: nowUtc(),
    action,
    // Null for T1: an event's first transition comes from nowhere, and a fixture that wrote the
    // destination twice would make the pipeline's activity log read as a status that never held.
    fromStatus: event.status || null,
    toStatus,
    actorKind,
    reasonCode: reasonCode || null,
    note: null
  });
  event.status = toStatus;
}

/** `EventsEventListItemView` — the pipeline row. */
function rowOf (event) {
  return {
    id: event.id,
    publicId: event.publicId,
    status: event.status,
    title: event.title,
    eventDate: event.eventDate + 'T00:00:00',
    guestCountPlanned: event.guestCountPlanned,
    contactName: event.contactName,
    acceptedProposalVersionNo: event.acceptedProposalVersionNo,
    createdAtUtc: event.createdAtUtc
  };
}

/** `EventsProposalVersionView` — the admin projection of one version. */
function versionOf (version) {
  return {
    versionNo: version.versionNo,
    status: version.status,
    currencyCode: version.currencyCode,
    totalMinor: version.totalMinor,
    minimumSpendMinor: version.minimumSpendMinor,
    roomFeeMinor: version.roomFeeMinor,
    depositRequiredMinor: version.depositRequiredMinor,
    termsText: version.termsText,
    expiresAtUtc: version.expiresAtUtc,
    // The guest address, shown on screen on purpose: dispatch is dark by default, so a member of
    // staff copies this link out of the page. Minted at DRAFT, like the server does it.
    publicToken: version.publicToken,
    contentHash: version.contentHash,
    createdAtUtc: version.createdAtUtc,
    sentAtUtc: version.sentAtUtc,
    lines: version.lines
  };
}

/** `EventsEventDetailView`. Carries versions and transitions; NO deposit and NO settlement. */
function detailOf (event) {
  return {
    id: event.id,
    publicId: event.publicId,
    storeId: Number(event.storeId),
    status: event.status,
    title: event.title,
    eventDate: event.eventDate + 'T00:00:00',
    startTime: event.startTime,
    endTime: event.endTime,
    timeZoneId: world.TIME_ZONE,
    guestCountPlanned: event.guestCountPlanned,
    contactName: event.contactName,
    contactEmail: event.contactEmail,
    contactPhone: event.contactPhone,
    companyName: event.companyName,
    source: event.source,
    acceptedProposalVersionNo: event.acceptedProposalVersionNo,
    createdAtUtc: event.createdAtUtc,
    dietary: event.dietary,
    versions: event.versions.map(versionOf),
    transitions: event.transitions,
    // The guest's own message becomes the event's first note, authored by nobody — `AuthorUserId` is
    // null for it, which is how a venue tells the enquiry's words from a colleague's.
    notes: event.notes
  };
}

/** `EventsPublicProposalView` — what the guest page reads. Never the admin projection. */
function publicViewOf (version, event) {
  return {
    token: version.publicToken,
    eventTitle: event.title,
    eventDate: event.eventDate,
    guestCountPlanned: event.guestCountPlanned,
    versionNo: version.versionNo,
    status: version.status,
    currencyCode: version.currencyCode,
    totalMinor: version.totalMinor,
    minimumSpendMinor: version.minimumSpendMinor,
    roomFeeMinor: version.roomFeeMinor,
    depositRequiredMinor: version.depositRequiredMinor,
    termsText: version.termsText,
    expiresAtUtc: version.expiresAtUtc,
    contentHash: version.contentHash,
    // The server's own gate, read by the page rather than re-derived from the status and a clock.
    isActionable: version.status === 'Sent',
    isAmendment: false,
    lines: version.lines
  };
}

/** `EventsLifecycleResultView` — what every lifecycle action answers. */
function lifecycleResult (event) {
  return {
    publicId: event.publicId,
    eventStatus: event.status,
    settlement: event.settlement ? settlementView(event.settlement) : null
  };
}

/** `EventsSettlementView`. */
function settlementView (settlement) {
  return {
    id: settlement.id,
    status: settlement.status,
    statementTotalMinor: settlement.statementTotalMinor,
    reconciledAtUtc: settlement.reconciledAtUtc,
    closedAtUtc: settlement.closedAtUtc,
    closedByUserId: settlement.closedByUserId,
    revision: settlement.revision,
    lines: settlement.lines
  };
}

/**
 * `EventsSettlementReadView` — the idempotent settlement read.
 *
 * `settlement: null` is an ANSWERED absence and the client reads it as one; it is a different fact
 * from the 404 the flag gives, which says nothing about whether a settlement exists.
 */
function settlementRead (event) {
  return {
    publicId: event.publicId,
    eventStatus: event.status,
    settlement: event.settlement ? settlementView(event.settlement) : null
  };
}

/**
 * `EventsSettlementService.RecomputeTotal` sums the line MAGNITUDES — a `DepositApplied` line and an
 * `Invoice` line both count positive, and the wire carries no sign convention that would say which
 * kinds subtract. Copied rather than improved: a fixture that netted them would let the page ship a
 * balance the server never produces.
 */
function recomputeTotal (settlement) {
  settlement.statementTotalMinor = settlement.lines.reduce((sum, line) => sum + Math.abs(line.amountMinor), 0);
}

/**
 * What a reconcile finds when it goes looking for a line's truth.
 *
 * The reconcile fetches each line's figure THROUGH A READ SEAM and compares it with what the venue
 * recorded, and which seam it asks is decided by the line's source:
 *
 *   Manual (an Adjustment)   nothing external to ask. An adjustment IS the operator's figure, so the
 *   InvoiceRef (an Invoice)  read seam answers the line itself and the line matches. That is what
 *                            makes "close -> add the invoice -> reconcile -> settle" a walk an
 *                            operator can complete on a deployment with no invoicing integration.
 *   Deposit, OrderRef,       a deposit's receipts and the POS journal. THIS FIXTURE HOLDS NEITHER,
 *   JournalRef               and neither is reachable in the walk it serves — no deposit is paid and
 *                            no pos-link is attached — so a line of that source would find no truth
 *                            and report a MISMATCH rather than being quietly matched to itself. A
 *                            fixture that answered the recorded figure for those too would make the
 *                            discrepancy state unreachable, and a settlement that can only ever
 *                            reconcile is not a reconciliation.
 */
function truthOf (line) {
  return line.sourceKind === 'Manual' || line.sourceKind === 'InvoiceRef' ? line.amountMinor : null;
}

/**
 * The settlement's opaque revision moves on every write.
 *
 * A STRING here, and never null, because this fixture stands in for a SQL Server host: `revision` is
 * a `rowversion` and a SQLite host has none, which is why the client tolerates null. Modelling the
 * null would silently retire the `If-Match` guard below — the one precondition this surface has.
 */
function bumpRevision (settlement) {
  settlement.revision = Buffer.from('ev-rev-' + (++settlement.revisionSeq)).toString('base64');
}

// ---- the public half ---------------------------------------------------------------------------
//
// NO TOKEN IS REQUIRED AND NONE IS LOOKED AT. These routes are `[AllowAnonymous]` on
// `EventsController`, so they are matched BEFORE the fixture's auth wall — matching them below it
// would 401 the guest and hide the property the guest journeys exist to check.

function routePublic (ctx) {
  const { method, body } = ctx;
  const events = slice(ctx);

  if (ctx.path === '/events/inquiries' && method === 'POST') {
    if (!body) { return validation(ctx, 'An inquiry body is required.'); }
    const storeId = body.storeId;
    const contactName = String(body.contactName || '').trim();
    const contactEmail = String(body.contactEmail || '').trim();
    const guests = body.guestCountPlanned;
    if (!contactName) { return validation(ctx, 'A contact name is required.'); }
    if (!contactEmail) { return validation(ctx, 'A contact email is required.'); }
    if (!(typeof guests === 'number' && guests > 0)) {
      return validation(ctx, 'A planned guest count is required.');
    }
    if (!storeId) { return validation(ctx, 'A storeId is required.'); }
    // TWO REAL REFUSALS THIS ROUTE HAS AND THIS FIXTURE DOES NOT GIVE, stated rather than forgotten
    // — and stated in prose rather than as unmodelled-refusal declarations, because that grammar
    // belongs with a route anchor and no `/events` route is anchored yet (see the file's closing
    // note):
    //
    //   404 EVENTS_STORE_NOT_FOUND  a storeId no store has. This fixture keeps no store REGISTRY —
    //                               `GET /stores/{id}` answers for every numeric id — so refusing one
    //                               here would make the fixture contradict itself.
    //   429 (carrying no code)      the per-IP limiter, ten enquiries a quarter hour, answering
    //                               `{ message }` and NOT problem+json, which is why the guest client
    //                               is the one place that gives that refusal a code at all. Modelled
    //                               here it would fire on nobody.

    // NO FLAG GATE, AND THAT IS THE PRODUCT'S CURRENT SHAPE — `F-EV-INQUIRY-UNGATED`, open for a
    // ruling. The write succeeds for a store whose admin surface answers 404 to every read, so the
    // guest is handed a reference for a booking the venue cannot see. Modelled exactly, so a journey
    // can walk that consequence rather than assert it.
    events.seq += 1;
    const id = 8000 + events.seq;
    const event = {
      id,
      publicId: guidFrom('events-inquiry-' + id),
      storeId: String(storeId),
      status: null,
      // `EventSource` is `ConsumerInquiry` or `Manual`. A venue reads this to tell an enquiry that
      // arrived through its own website from one a colleague typed in.
      source: 'ConsumerInquiry',
      // Blank becomes the server's own placeholder rather than null: the pipeline row prints the
      // title, and a row with no title is a booking nobody can pick out of a list.
      title: String(body.title || '').trim() || 'Event inquiry',
      eventDate: String(body.eventDate || '').slice(0, 10),
      startTime: body.startTime || null,
      endTime: body.endTime || null,
      guestCountPlanned: guests,
      contactName,
      contactEmail,
      contactPhone: body.contactPhone || null,
      companyName: body.companyName || null,
      createdAtUtc: nowUtc(),
      acceptedProposalVersionNo: null,
      dietary: null,
      versions: [],
      transitions: [],
      notes: [],
      settlement: null,
      acceptance: null
    };
    if (String(body.message || '').trim()) {
      event.notes.push({
        id: id * 10,
        // NULL, and it matters: the guest is not a user of this system, and an author id invented
        // here would attribute their words to a member of staff.
        authorUserId: null,
        body: String(body.message).trim(),
        createdAtUtc: event.createdAtUtc
      });
    }
    events.events.push(event);
    // T1. The actor is the GUEST and there is no user id to carry.
    transition(event, 'T1', 'Inquiry', 'Guest', null);
    // `EventsInquiryConfirmationView` — the public id, the status, and a sentence. It names NOTHING
    // about the venue, which is what makes it safe to answer to whoever holds the form.
    ctx.send(200, {
      publicId: event.publicId,
      status: event.status,
      message: 'Thanks — your inquiry has been received. The venue will reply with a proposal.'
    });
    return true;
  }

  const read = /^\/events\/proposals\/([^/]+)$/.exec(ctx.path);
  if (read && method === 'GET') {
    const found = findByToken(ctx, decodeURIComponent(read[1]));
    if (!found) { return proposalNotFound(ctx); }
    if (found.standing) { ctx.send(200, found.standing); return true; }
    // A DRAFT is not readable. The token exists from the moment the version is drafted, and answering
    // one before it is sent would show a guest an offer the venue has not made.
    if (found.version.status === 'Draft') { return proposalNotFound(ctx); }
    // UNGATED, and that is this route's shape rather than an omission here: `GetPublicAsync` performs
    // no store refinement on this branch. It is recorded against the module as an open read-side
    // leak, of lower severity than the two writes, which were closed.
    ctx.send(200, publicViewOf(found.version, found.event));
    return true;
  }

  const accept = /^\/events\/proposals\/([^/]+)\/accept$/.exec(ctx.path);
  if (accept && method === 'POST') {
    const token = decodeURIComponent(accept[1]);
    const found = findByToken(ctx, token);
    if (!found) { return proposalNotFound(ctx); }

    // ---- THE GATE (`F-EV-ACCEPT-UNGATED`, `EventsProposalService.GuardStoreEnabledAsync`) --------
    //
    // Placed where the token first resolves the store, and BEFORE the version-status switch below, so
    // it covers the idempotent replay of an already-accepted token as well as a first acceptance.
    // Both are writes as far as a venue with the module off is concerned: one records a guest's
    // consent, the other re-serves a receipt for a booking that venue cannot see.
    if (!ctx.flagEffective(found.event.storeId, CORE_FLAG)) { return proposalNotFound(ctx); }

    if (found.standing) { return acceptStanding(ctx, token, found.standing, body); }

    const { event, version } = found;
    if (version.status === 'Draft') { return proposalNotFound(ctx); }
    if (version.status === 'Superseded') {
      ctx.problem(409, 'EVENTS_PROPOSAL_SUPERSEDED', 'A newer version has been sent.');
      return true;
    }
    if (version.status === 'Accepted') {
      // The server replays rather than writing a second receipt (`EventsWriteGuards.BuildReplay`).
      ctx.send(200, event.acceptance);
      return true;
    }
    if (version.status !== 'Sent') { return stateRefusal(ctx, event.status, []); }
    if (version.expiresAtUtc && Date.parse(version.expiresAtUtc) <= Date.now()) {
      ctx.problem(409, 'EVENTS_PROPOSAL_EXPIRED', 'This offer has expired.');
      return true;
    }

    version.status = 'Accepted';
    event.acceptedProposalVersionNo = version.versionNo;
    // T5. The actor is the GUEST with no user id — the acceptance is anonymous by construction, and
    // the name and address in the body are recorded verbatim on the append-only receipt rather than
    // being validated into an identity.
    transition(event, 'T5', 'Accepted', 'Guest', null);
    event.receipt = {
      proposalContentHash: version.contentHash,
      acceptorName: (body && body.acceptorName) || null,
      acceptorEmail: (body && body.acceptorEmail) || null,
      acceptedAtUtc: nowUtc()
    };
    // T8, in the SAME transaction: a version requiring no deposit has nothing left to wait for, so
    // acceptance confirms the booking outright and the system is the actor. A version that DOES
    // require one stays `Accepted` until the deposit is paid (T7 then T9) — a money path this fixture
    // does not model, and does not pretend to.
    if (!version.depositRequiredMinor) {
      transition(event, 'T8', 'Confirmed', 'System', null);
    }
    event.acceptance = {
      publicId: event.publicId,
      eventStatus: event.status,
      acceptedVersionNo: version.versionNo,
      proposalContentHash: version.contentHash,
      acceptedAtUtc: event.receipt.acceptedAtUtc,
      wasAmendment: false
    };
    ctx.send(200, event.acceptance);
    return true;
  }

  const decline = /^\/events\/proposals\/([^/]+)\/decline$/.exec(ctx.path);
  if (decline && method === 'POST') {
    const token = decodeURIComponent(decline[1]);
    const found = findByToken(ctx, token);
    if (!found) { return proposalNotFound(ctx); }
    // The same gate, for the same reason: a decline writes a transition onto a venue's event and
    // ends the booking.
    if (!ctx.flagEffective(found.event.storeId, CORE_FLAG)) { return proposalNotFound(ctx); }

    if (found.standing) {
      found.standing.status = 'Declined';
      found.standing.isActionable = false;
      ctx.send(200, { declinedVersionNo: found.standing.versionNo, declinedAtUtc: nowUtc() });
      return true;
    }
    const { event, version } = found;
    if (version.status !== 'Sent') { return stateRefusal(ctx, event.status, []); }
    version.status = 'Declined';
    transition(event, 'T6', 'Lost', 'Guest', 'Declined');
    ctx.send(200, {
      publicId: event.publicId,
      eventStatus: event.status,
      versionStatus: version.status,
      wasAmendment: false
    });
    return true;
  }

  return false;
}

/**
 * The standing world's accept, unchanged from what `api-server.js` served before this file — down to
 * the receipt shape, which carries the acceptor's name and address as well.
 */
function acceptStanding (ctx, token, proposal, body) {
  if (!proposal.isActionable) {
    const code = proposal.status === 'Superseded' ? 'EVENTS_PROPOSAL_SUPERSEDED' : 'EVENTS_PROPOSAL_EXPIRED';
    ctx.problem(409, code, 'This version can no longer be accepted.');
    return true;
  }
  if (ctx.state.acceptances[token]) {
    ctx.send(200, ctx.state.acceptances[token]);
    return true;
  }
  const receipt = {
    acceptedVersionNo: proposal.versionNo,
    acceptedAtUtc: nowUtc(),
    proposalContentHash: proposal.contentHash,
    acceptorName: (body && body.acceptorName) || null,
    acceptorEmail: (body && body.acceptorEmail) || null
  };
  ctx.state.acceptances[token] = receipt;
  proposal.status = 'Accepted';
  proposal.isActionable = false;
  ctx.send(200, receipt);
  return true;
}

// ---- the admin half ----------------------------------------------------------------------------
//
// Every route below is store-scoped and behind `Events.Core`, reads INCLUDED — which is the whole
// difference between this module and Workforce. §9's rule for Events is INVISIBLE, not read-only: a
// store that has not been switched on sees no pipeline, no event, no run sheet and no notification
// health. The gate is applied once, before the routing, because a fixture that gated only some of the
// reads would let the pipeline page ship half-lit.

function route (ctx) {
  const match = /^\/events\/admin\/([^/]+)(\/.*)?$/.exec(ctx.path);
  if (!match) { return false; }

  const storeId = match[1];
  const rest = match[2] || '';
  const events = slice(ctx);

  if (!ctx.flagEffective(storeId, CORE_FLAG)) { return disabled(ctx); }

  // ---- the pipeline list ------------------------------------------------------------------------
  if (rest === '/events' && ctx.method === 'GET') {
    // The page sends `status`/`from`/`to` as filters. An unsupported filter answers an empty list
    // rather than the rows — a fixture that silently ignored a filter it was sent would let a broken
    // query string pass.
    const status = ctx.url.searchParams.get('status');
    const standing = String(storeId) === String(world.STORE_ID) ? [world.ADMIN_EVENT_ROW] : [];
    const rows = standing
      .concat(events.events.filter(event => String(event.storeId) === String(storeId)).map(rowOf))
      .filter(row => !status || status === row.status);
    ctx.send(200, rows);
    return true;
  }

  if (rest === '/notifications/health' && ctx.method === 'GET') {
    ctx.send(200, world.ADMIN_NOTIFICATION_HEALTH);
    return true;
  }

  const one = /^\/events\/([^/]+)(\/.*)?$/.exec(rest);
  if (!one) { return false; }
  const eventId = one[1];
  const facet = one[2] || '';

  // ---- the standing event: reads only -----------------------------------------------------------
  //
  // A POST or PUT to any of these falls through rather than being quietly accepted, which is the
  // honest answer for a contract this half does not hold.
  if (String(eventId) === String(world.ADMIN_EVENT_ID) && String(storeId) === String(world.STORE_ID)) {
    if (ctx.method !== 'GET') { return false; }
    if (facet === '') { ctx.send(200, world.ADMIN_EVENT_DETAIL); return true; }
    // Core is enough for the deposit READ: only the deposit ISSUE passes `requireDepositsFlag`, so
    // `Events.Deposits` gates minting a new obligation and never reading an existing one. Copied
    // deliberately — a fixture that also gated the read would hide a guest's paid deposit behind a
    // switch, which is the case `EventsDepositsController` says out loud it must not do.
    if (facet === '/deposits') { ctx.send(200, world.ADMIN_DEPOSITS); return true; }
    if (facet === '/run-sheet') { ctx.send(200, world.ADMIN_RUN_SHEET); return true; }
    if (facet === '/settlement') {
      // The one facet with a second gate. `Events.Settlement` is deny-closed and gates the GET as
      // well as the mutations, so "Core on, settlement closed" — the ordinary state of a venue
      // running events without the money machine — answers `EVENTS_DISABLED` here rather than a
      // document.
      if (!ctx.flagEffective(storeId, SETTLEMENT_FLAG)) { return disabled(ctx); }
      ctx.send(200, world.ADMIN_SETTLEMENT);
      return true;
    }
    return false;
  }

  // ---- the living event -------------------------------------------------------------------------
  const event = findEvent(events, storeId, eventId);
  if (!event) { return notFound(ctx); }

  if (facet === '' && ctx.method === 'GET') { ctx.send(200, detailOf(event)); return true; }

  if (facet === '/deposits' && ctx.method === 'GET') {
    // An answered absence: this walk mints no deposit, and `[]` is a different fact from a read that
    // failed.
    ctx.send(200, []);
    return true;
  }

  if (facet === '/run-sheet' && ctx.method === 'GET') {
    // The run sheet has its OWN absence dialect — a 404 with its own code — and it is the one facet
    // that can honestly say "there is none yet".
    ctx.problem(404, 'EVENTS_RUNSHEET_NOT_FOUND', 'No run sheet has been generated for this event.');
    return true;
  }

  // ---- the proposal (T2, T3) --------------------------------------------------------------------
  if (facet === '/proposal-versions' && ctx.method === 'POST') {
    if (event.status !== 'Inquiry' && event.status !== 'Proposing') {
      // T4 (from ProposalSent) and T16 (from Accepted) are real transitions this fixture does not
      // model. Refusing is the honest answer; accepting would let a journey walk a revision path no
      // server here performs.
      return stateRefusal(ctx, event.status, []);
    }
    const body = ctx.body || {};
    const lines = Array.isArray(body.lines) ? body.lines : [];
    if (!lines.length) { return validation(ctx, 'A proposal version needs at least one line.'); }
    for (const line of lines) {
      if (!PROPOSAL_LINE_KINDS.includes(line.kind)) {
        return validation(ctx, '\'' + line.kind + '\' is not a valid proposal line kind.');
      }
      if (Number(line.quantity) < 0 || Number(line.unitPriceMinor) < 0) {
        return validation(ctx, 'A proposal line cannot be negative.');
      }
    }
    // The currency RESTATES the store's, and the store wins. A disagreement is refused rather than
    // silently corrected: an offer denominated in a currency the venue does not trade in is a figure
    // nobody agreed to.
    if (body.currencyCode && body.currencyCode !== world.CURRENCY) {
      return validation(ctx, 'This store trades in ' + world.CURRENCY + '.');
    }
    const versionNo = event.versions.length + 1;
    const priced = lines.map((line, index) => ({
      lineNo: index + 1,
      kind: line.kind,
      description: line.description || null,
      quantity: line.quantity,
      unitPriceMinor: line.unitPriceMinor,
      // The SERVER prices the line. The caller sends a unit price and a quantity; an amount it also
      // sent would be a total the caller computed, and two sources for one figure is one too many.
      amountMinor: Math.round(Number(line.quantity || 0) * Number(line.unitPriceMinor || 0)),
      vatRate: line.vatRate
    }));
    const version = {
      versionNo,
      // A Draft carries no content hash: it is settled at SEND, which is what makes a sent version
      // immutable and its acceptance receipt bindable to what was on screen. The TOKEN, though, is
      // minted here — the server mints it with the row — and the public read refuses a Draft.
      status: 'Draft',
      currencyCode: body.currencyCode || null,
      minimumSpendMinor: body.minimumSpendMinor || 0,
      roomFeeMinor: body.roomFeeMinor || 0,
      depositRequiredMinor: body.depositRequiredMinor || 0,
      termsText: body.termsText || null,
      expiresAtUtc: body.expiresAtUtc || null,
      createdAtUtc: nowUtc(),
      sentAtUtc: null,
      publicToken: guidFrom('events-token-' + event.id + '-' + versionNo),
      contentHash: null,
      totalMinor: priced.reduce((sum, line) => sum + line.amountMinor, 0),
      lines: priced
    };
    event.versions.push(version);
    if (event.status === 'Inquiry') { transition(event, 'T2', 'Proposing', 'Admin', null); }
    ctx.send(200, versionOf(version));
    return true;
  }

  const send = /^\/proposal-versions\/([^/]+)\/send$/.exec(facet);
  if (send && ctx.method === 'POST') {
    const version = event.versions.find(v => String(v.versionNo) === String(send[1]));
    if (!version) {
      ctx.problem(404, 'EVENTS_PROPOSAL_NOT_FOUND', 'This event has no such version.');
      return true;
    }
    // An already-sent version replays unchanged: a double-pressed button must not mint a second
    // content hash for an offer the guest has already been shown.
    if (version.status === 'Sent') { ctx.send(200, versionOf(version)); return true; }
    if (version.status !== 'Draft') { return proposalInvalid(ctx, 'Only a Draft version can be sent.'); }
    // The send preflight, and every one of these is about the VERSION rather than the event — which
    // is why they are `EVENTS_PROPOSAL_INVALID` and not `EVENTS_STATE`.
    if (!version.currencyCode) {
      return proposalInvalid(ctx,
        'A proposal must state the currency its amounts are in before it can be sent.');
    }
    if (!version.lines.length) {
      return proposalInvalid(ctx, 'A proposal must have at least one line before it can be sent.');
    }
    if (!version.expiresAtUtc) {
      return proposalInvalid(ctx, 'A proposal must have an expiry before it can be sent.');
    }
    if (Date.parse(version.expiresAtUtc) <= Date.now()) {
      return proposalInvalid(ctx, 'The proposal expiry must be in the future.');
    }
    if (event.status !== 'Proposing') { return stateRefusal(ctx, event.status, []); }

    version.status = 'Sent';
    version.sentAtUtc = nowUtc();
    // Settled over the content the guest will be shown, and re-verified at acceptance. This is what
    // the receipt binds to, so it must be computed from the figures rather than from the id.
    version.contentHash = digest(
      JSON.stringify(version.lines) + '|' + version.totalMinor + '|' + (version.termsText || '')).slice(0, 16);
    // A previously sent version is superseded by this one, and still answers with its own content:
    // the guest who was sent it must be able to see what they were sent.
    event.versions.forEach((other) => {
      if (other !== version && other.status === 'Sent') { other.status = 'Superseded'; }
    });
    transition(event, 'T3', 'ProposalSent', 'Admin', null);
    ctx.send(200, versionOf(version));
    return true;
  }

  // ---- the tail (T11, T12, T13) ------------------------------------------------------------------
  if (facet === '/start-service' && ctx.method === 'POST') {
    // `Events.Core` ONLY. T11 is not a settlement action, and gating it on the money flag would stop
    // a venue starting service on a booking it is standing in the middle of.
    if (event.status === 'InService') { ctx.send(200, lifecycleResult(event)); return true; }
    if (event.status !== 'Confirmed') { return stateRefusal(ctx, event.status, ['Cancel']); }
    transition(event, 'T11', 'InService', 'Admin', null);
    ctx.send(200, lifecycleResult(event));
    return true;
  }

  if (facet === '/close' && ctx.method === 'POST') {
    // T12 and everything below it is behind `Events.Settlement` as well as `Events.Core`.
    if (!ctx.flagEffective(storeId, SETTLEMENT_FLAG)) { return disabled(ctx); }
    if (event.status !== 'InService') { return stateRefusal(ctx, event.status, ['StartService']); }
    // The settlement is GENERATED by close, in `Draft`, and it is empty here because this walk holds
    // no paid deposit: the server appends a `DepositApplied` line only when one exists.
    event.settlement = {
      id: 9000 + event.id,
      status: 'Draft',
      statementTotalMinor: 0,
      reconciledAtUtc: null,
      closedAtUtc: null,
      closedByUserId: null,
      revisionSeq: 0,
      revision: null,
      lines: []
    };
    bumpRevision(event.settlement);
    transition(event, 'T12', 'Settling', 'Admin', null);
    ctx.send(200, lifecycleResult(event));
    return true;
  }

  if (facet === '/settlement' && ctx.method === 'GET') {
    if (!ctx.flagEffective(storeId, SETTLEMENT_FLAG)) { return disabled(ctx); }
    ctx.send(200, settlementRead(event));
    return true;
  }

  if (facet.startsWith('/settlement/') && ctx.method === 'POST') {
    if (!ctx.flagEffective(storeId, SETTLEMENT_FLAG)) { return disabled(ctx); }
    const settlement = event.settlement;
    if (!settlement) {
      return settlementState(ctx, 'No settlement exists for this event yet; close the event first.');
    }

    // `EventsSettlementConcurrency.GuardIfMatch`, and the split between its two refusals is
    // load-bearing: an ABSENT precondition is fixed by a different request (fetch the revision), a
    // STALE one by repeating this one. Collapsing them into a single "retry" told a caller that sent
    // no header at all to do the one thing that could never work.
    const ifMatch = ctx.req.headers['if-match'];
    if (settlement.revision && !ifMatch) {
      ctx.problem(400, 'EVENTS_REVISION_REQUIRED', 'This mutation must carry the settlement revision.');
      return true;
    }
    if (settlement.revision && ifMatch !== settlement.revision) {
      ctx.problem(409, 'EVENTS_CONFLICT', 'The settlement has moved since that revision.',
        { conflictKind: 'settlement-revision', retryable: true });
      return true;
    }

    if (facet === '/settlement/lines') {
      const body = ctx.body || {};
      if (!AUTHORABLE_SETTLEMENT_LINE_KINDS.includes(body.kind)) {
        return settlementState(ctx,
          'Only Invoice or Adjustment lines can be added directly; deposit and POS lines are generated.');
      }
      if (settlement.status !== 'Draft' && settlement.status !== 'Discrepancy') {
        return settlementState(ctx, 'The settlement can no longer be edited; it is ' + settlement.status + '.');
      }
      if (!Number.isInteger(body.amountMinor)) {
        return validation(ctx, 'An amount in minor units is required.');
      }
      if (body.kind === 'Adjustment' && !String(body.adjustmentReason || '').trim()) {
        return validation(ctx, 'An adjustment line needs a reason.');
      }
      settlement.lines.push({
        lineNo: settlement.lines.length + 1,
        kind: body.kind,
        // DERIVED from the kind and never taken from the caller: the server overwrites whatever is
        // sent, so a value on the wire would read as a choice the operator made and did not.
        sourceKind: body.kind === 'Invoice' ? 'InvoiceRef' : 'Manual',
        sourceReference: body.sourceReference || null,
        amountMinor: body.amountMinor,
        // Truth is null until a reconcile has fetched it — never a copy of the recorded amount, which
        // would make an unverified line read as a matched one.
        truthAmountMinor: null,
        matchState: 'Unverified',
        note: body.note || null,
        adjustmentReason: body.adjustmentReason || null
      });
      // A statement that has taken a new line is no longer reconciled.
      if (settlement.status === 'Discrepancy') { settlement.status = 'Draft'; }
      recomputeTotal(settlement);
      bumpRevision(settlement);
      // The bare view, not the read envelope: this route answers the settlement itself.
      ctx.send(200, settlementView(settlement));
      return true;
    }

    if (facet === '/settlement/reconcile') {
      // Reconciling is only legal once the event is SETTLING. Asking from `Confirmed` or `InService`
      // is refused outright, because a statement that is still taking POS checks has no truth to be
      // compared against yet.
      if (event.status !== 'Settling') { return stateRefusal(ctx, event.status, ['Close']); }
      if (settlement.status !== 'Draft' && settlement.status !== 'Discrepancy') {
        return settlementState(ctx, 'This settlement is already ' + settlement.status + '.');
      }
      settlement.lines.forEach((line) => {
        line.truthAmountMinor = truthOf(line);
        line.matchState = line.truthAmountMinor === line.amountMinor ? 'Matched' : 'Mismatch';
      });
      const mismatched = settlement.lines.filter(line => line.matchState === 'Mismatch');
      if (mismatched.length) {
        settlement.status = 'Discrepancy';
        settlement.reconciledAtUtc = null;
      } else {
        settlement.status = 'Reconciled';
        settlement.reconciledAtUtc = nowUtc();
      }
      bumpRevision(settlement);
      ctx.send(200, {
        settlement: settlementView(settlement),
        mismatchedLineNos: mismatched.map(line => line.lineNo)
      });
      return true;
    }

    if (facet === '/settlement/close') {
      // T13. A statement that has not been reconciled is refused with its OWN code, which the page
      // turns into "press reconcile first" rather than printing a bare code at an operator.
      if (settlement.status !== 'Reconciled') {
        ctx.problem(409, 'EVENTS_SETTLEMENT_NOT_RECONCILED',
          'This statement must be reconciled before it can be closed.',
          { conflictKind: 'settlement-not-reconciled', retryable: false });
        return true;
      }
      settlement.status = 'Closed';
      settlement.closedAtUtc = nowUtc();
      settlement.closedByUserId = ctx.caller ? ctx.caller.id : null;
      bumpRevision(settlement);
      transition(event, 'T13', 'Settled', 'Admin', null);
      ctx.send(200, lifecycleResult(event));
      return true;
    }
  }

  return false;
}

module.exports = { fresh, route, routePublic };

// ---- WHAT THIS FILE IS NOT YET COMPARED AGAINST ------------------------------------------------
//
// NO ROUTE HERE CARRIES A DIVERGENCE ANCHOR, so `npm run test:e2e:fixture-divergence` does not
// compare a single one of these refusals against a real checkout. That is the state these routes were
// already in when they lived in `api-server.js` — no anchor there either — and it is recorded rather
// than left for somebody to assume the opposite from the neighbouring files, which ARE anchored.
//
// It matters most for the gate: the accept and decline refusals modelled here exist on
// `lane/ev-accept-gate` and NOT on the integration tip, so anchoring these two routes would report
// this fixture as AHEAD of one checkout and level with the other — which is the correct answer and
// exactly the kind a lane needs before it walks a journey. Anchoring the Events family is its own
// piece of work: every refusal on an anchored route must then be modelled or declared, and this
// surface has roughly forty across five controllers.
