#!/usr/bin/env python3
"""
Lane 0 instrument -- classify a venue's supplier invoices by how their line data arrives.

NOT RUN BY THIS LANE. No credential for any real venue exists on this machine, so nothing
here has been executed against Tripletex. It is written so that the spike becomes a
twenty-minute task the moment somebody holds a real venue's employee token.

WHAT IT DOES (read-only apart from the mandatory auth handshake)
  1. PUT  /v2/token/session/:create   -- the standard Tripletex handshake. This is the ONE
     state-creating call: it mints a short-lived session token. There is no read-only way to
     authenticate to this API. Everything after it is a GET.
  2. GET  /v2/supplierInvoice         -- headers for an invoice-date window.
  3. GET  /v2/document/{id}/content   -- for each voucher that has an ediDocument, the bytes.
  It never approves, rejects, pays, posts, uploads or modifies anything.

THE CLASSIFICATION (the taxonomy is the vendor's own, confirmed against the live
https://tripletex.no/v2/swagger.json on 2026-08-03, not from memory):

  Voucher carries three INDEPENDENT document slots; the swagger says a voucher "may have both
  a document, an attachment and an ediDocument".
    ediDocument -> "created based on a machine readable document (such as EHF or EFO/NELFO)"
    attachment  -> "provided from an external source ... This is always a PDF"
    document    -> "generated by the system ... always a PDF"
  And supplierVoucherType is TYPE_SUPPLIER_INVOICE_SIMPLE | TYPE_SUPPLIER_INVOICE_DETAILED;
  orderLines[] is populated only for DETAILED.

  Class A  EHF/machine-readable  ediDocument present AND its bytes parse as UBL Invoice-2 or
                                 CreditNote-2. Full per-line quantity + UN/CEFACT unit code +
                                 net price + seller article number + GTIN are recoverable.
  Class B  DETAILED order lines  orderLines[] non-empty. Per-line description, count, unit
                                 price ex VAT, line amount ex VAT -- but NO unit code, so the
                                 per-pack/per-unit basis cannot be established from the line.
  Class C  PDF only              attachment or document present, no ediDocument, no orderLines.
                                 Posting totals only. No quantity, no unit, no article number.
  Class D  Header only           no document of any kind. Totals only.

USAGE
  export TT_CONSUMER_TOKEN=...     # never pass a token as an argv -- it lands in shell history
  export TT_EMPLOYEE_TOKEN=...
  python3 classify-invoices.py --from 2026-05-01 --to 2026-08-01 [--dump-ehf DIR]

  --dump-ehf writes the EHF XML per Class A invoice so MarginEhfInvoiceParser can be run over
  real documents. Those files are a real venue's commercial terms: keep them in the lane
  directory, never commit them.

OUTPUT is by SHAPE only -- counts per class, per-line field-fill rates, and a per-invoice row
carrying supplier ORG NUMBER (not name) so the same supplier is recognisable across invoices
without publishing who the venue buys from. It prints no token and no amount.
"""

import argparse
import base64
import collections
import datetime as dt
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

BASE = "https://tripletex.no/v2"
CBC = "{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}"
CAC = "{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}"
UBL_INVOICE = "{urn:oasis:names:specification:ubl:schema:xsd:Invoice-2}Invoice"
UBL_CREDITNOTE = "{urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2}CreditNote"

# The nested fields the ingest needs. Tripletex returns a thin projection unless asked.
FIELDS = (
    "id,invoiceNumber,invoiceDate,isCreditNote,amountExcludingVat,currency(code),"
    "supplier(id,organizationNumber),"
    "orderLines(id,description,count,unitPriceExcludingVatCurrency,amountExcludingVatCurrency,"
    "product(id,number,ean)),"
    "voucher(id,supplierVoucherType,ediDocument(id,fileName,mimeType,size),"
    "attachment(id,fileName,mimeType,size),document(id,fileName,mimeType,size))"
)


def _request(method, url, headers, body=None):
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            return r.status, r.read(), dict(r.headers)
    except urllib.error.HTTPError as e:
        return e.code, e.read(), dict(e.headers)


def session_token(consumer, employee):
    # Expiry is a date; Tripletex rejects a session request without one.
    exp = (dt.date.today() + dt.timedelta(days=1)).isoformat()
    url = "%s/token/session/:create?consumerToken=%s&employeeToken=%s&expirationDate=%s" % (
        BASE, consumer, employee, exp)
    status, body, _ = _request("PUT", url, {"Accept": "application/json"})
    if status != 200:
        sys.exit("session handshake failed: HTTP %d (body withheld -- it can echo the token)" % status)
    return json.loads(body)["value"]["token"]


def auth_header(token):
    raw = ("0:%s" % token).encode("utf-8")
    return {"Authorization": "Basic " + base64.b64encode(raw).decode("ascii"),
            "Accept": "application/json"}


def classify_ehf(xml_bytes):
    """What the EHF actually carries per line -- the half that decides the ship question."""
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError as e:
        return {"parses": False, "why": str(e)[:120]}
    if root.tag == UBL_INVOICE:
        line_tag, qty_tag = CAC + "InvoiceLine", CBC + "InvoicedQuantity"
    elif root.tag == UBL_CREDITNOTE:
        line_tag, qty_tag = CAC + "CreditNoteLine", CBC + "CreditedQuantity"
    else:
        return {"parses": False, "why": "root is %s, not a UBL invoice or credit note" % root.tag}

    lines = root.findall(line_tag)
    fill = collections.Counter()
    units = collections.Counter()
    for ln in lines:
        q = ln.find(qty_tag)
        if q is not None:
            fill["quantity"] += 1
            u = q.get("unitCode")
            if u:
                fill["unit_code"] += 1
                units[u] += 1
        item = ln.find(CAC + "Item")
        price = ln.find(CAC + "Price")
        if ln.find(CBC + "LineExtensionAmount") is not None:
            fill["line_net_amount"] += 1
        if price is not None and price.find(CBC + "PriceAmount") is not None:
            fill["item_net_price"] += 1
        if price is not None and price.find(CBC + "BaseQuantity") is not None:
            fill["price_base_quantity"] += 1
        if item is not None:
            if item.find(CAC + "SellersItemIdentification/" + CBC + "ID") is not None:
                fill["seller_article_number"] += 1
            if item.find(CAC + "StandardItemIdentification/" + CBC + "ID") is not None:
                fill["gtin"] += 1
            if item.find(CBC + "Name") is not None:
                fill["item_name"] += 1
    return {"parses": True, "lines": len(lines), "fill": dict(fill), "unit_codes": dict(units)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="date_from", required=True, help="inclusive yyyy-mm-dd")
    ap.add_argument("--to", dest="date_to", required=True, help="INCLUSIVE yyyy-mm-dd")
    ap.add_argument("--dump-ehf", dest="dump", default=None)
    args = ap.parse_args()

    consumer = os.environ.get("TT_CONSUMER_TOKEN")
    employee = os.environ.get("TT_EMPLOYEE_TOKEN")
    if not consumer or not employee:
        sys.exit("set TT_CONSUMER_TOKEN and TT_EMPLOYEE_TOKEN in the environment")

    headers = auth_header(session_token(consumer, employee))

    # Tripletex invoiceDateTo is EXCLUSIVE. Normalise so --to means what a human means.
    to_exclusive = (dt.date.fromisoformat(args.date_to) + dt.timedelta(days=1)).isoformat()

    invoices, offset = [], 0
    while True:
        url = "%s/supplierInvoice?invoiceDateFrom=%s&invoiceDateTo=%s&from=%d&count=1000&fields=%s" % (
            BASE, args.date_from, to_exclusive, offset, urllib.parse.quote(FIELDS, safe="(),"))
        status, body, _ = _request("GET", url, headers)
        if status == 403:
            print("ENTITLEMENT: NO -- GET /supplierInvoice returned 403.")
            print("  The employee token was minted without the supplier-invoice entitlement.")
            print("  Re-minting is a venue action: the token owner edits the token's entitlements")
            print("  in Tripletex (a token can never hold an entitlement its owner lacks).")
            sys.exit(2)
        if status != 200:
            sys.exit("GET /supplierInvoice -> HTTP %d" % status)
        page = json.loads(body)["values"]
        invoices.extend(page)
        if len(page) < 1000:
            break
        offset += len(page)

    print("ENTITLEMENT: YES -- GET /supplierInvoice returned 200.")
    print("window %s..%s inclusive, %d invoices\n" % (args.date_from, args.date_to, len(invoices)))

    if args.dump:
        os.makedirs(args.dump, exist_ok=True)

    counts = collections.Counter()
    print("%-10s %-4s %-12s %-9s %-6s %s" % ("class", "cn", "supplier-org", "vtype", "lines", "detail"))
    for inv in invoices:
        v = inv.get("voucher") or {}
        edi, att, doc = v.get("ediDocument"), v.get("attachment"), v.get("document")
        lines = inv.get("orderLines") or []
        org = (inv.get("supplier") or {}).get("organizationNumber") or "?"
        vtype = (v.get("supplierVoucherType") or "?").replace("TYPE_SUPPLIER_INVOICE_", "")
        cn = "CN" if inv.get("isCreditNote") else ""

        if edi:
            status, content, hdrs = _request("GET", "%s/document/%d/content" % (BASE, edi["id"]), headers)
            if status != 200:
                cls, detail = "A?", "ediDocument present but content -> HTTP %d" % status
            else:
                ctype = hdrs.get("Content-Type", "")
                result = classify_ehf(content)
                if result["parses"]:
                    cls = "A-EHF"
                    detail = "ctype=%s %s" % (ctype.split(";")[0], json.dumps(result))
                    if args.dump:
                        open(os.path.join(args.dump, "%d.xml" % inv["id"]), "wb").write(content)
                else:
                    cls, detail = "A?", "ediDocument not UBL: %s (%s)" % (result["why"], ctype)
        elif lines:
            filled = sum(1 for l in lines if l.get("count") is not None
                         and l.get("amountExcludingVatCurrency") is not None)
            with_art = sum(1 for l in lines if (l.get("product") or {}).get("number"))
            with_ean = sum(1 for l in lines if (l.get("product") or {}).get("ean"))
            cls = "B-LINES"
            detail = "count+amount filled %d/%d, article# %d, ean %d, NO unit code available" % (
                filled, len(lines), with_art, with_ean)
        elif att or doc:
            d = att or doc
            cls = "C-PDF"
            detail = "%s mime=%s size=%s -- totals only" % (
                "attachment" if att else "document", d.get("mimeType"), d.get("size"))
        else:
            cls, detail = "D-HEADER", "no document of any kind"

        counts[cls] += 1
        print("%-10s %-4s %-12s %-9s %-6d %s" % (cls, cn, org, vtype, len(lines), detail))

    total = sum(counts.values()) or 1
    print("\n--- verdict input ---")
    for cls, n in counts.most_common():
        print("  %-10s %3d  %5.1f%%" % (cls, n, 100.0 * n / total))
    print("\nSTOP if Class C+D is the majority: the feature degrades to watching invoice totals,")
    print("which is not worth the Lane 2-7 build (docs/plans/TRIPLETEX-INVOICE-INGEST.md, Lane 0).")


if __name__ == "__main__":
    import urllib.parse  # noqa: E402  (kept local to the entry point, argparse-only import above)
    main()
