#!/usr/bin/env bash
# Mutation proof for L-XZ-RESIDUAL-SITES.
#
# IN A SCRATCH EXPORT, NEVER IN PLACE. The sibling lane's proof mutated the shared working tree and
# restored it with a trap while other lanes were running in it. It restored cleanly; this does not
# rely on that a second time. Every mutation below happens inside a throwaway copy under
# $SCRATCH, and the tree this script is run from is never written to.
#
# TWO KINDS OF PROOF:
#   A. BEFORE/AFTER. The new tests are run against the UNPORTED baseline (b150668b). They must FAIL
#      there, printing the real `−—`. A test that passes on the code it claims to fix proves nothing.
#   B. MUTATIONS. Each mutation is a plausible wrong version of this lane's change, applied to the
#      ported export. Every one must go red, and the run records WHICH assertion caught it.
#
# Usage:  bash lanes/L-XZ-RESIDUAL-SITES/mutation-proof.sh
set -u

LANE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRATCH="${SCRATCH:-/private/tmp/claude-501/-Users-svendaneel-okam/766072d3-8965-4c45-be67-76b407d86aaf/scratchpad}/xz-residual-mut"
SHARED_MODULES="/Users/svendaneel/okam/Web-modules/node_modules"
SPEC="test/xz-residual-sites.test.js test/xz-negated-absence.test.js"

rm -rf "$SCRATCH"; mkdir -p "$SCRATCH"

# An export of the CURRENT (ported) tree, tracked files plus the two test files, without .git.
export_tree () {
  local dest="$1"
  mkdir -p "$dest"
  ( cd "$LANE_ROOT" && tar --exclude=./.git --exclude=./node_modules --exclude=./core \
      --exclude=./.nuxt --exclude=./dist -cf - . ) | ( cd "$dest" && tar -xf - )
  ln -s "$SHARED_MODULES" "$dest/node_modules"
  ln -s "$LANE_ROOT/core" "$dest/core"
}

run () {  # run <dir> -> the whole jest transcript
  ( cd "$1" && npx jest $SPEC --coverage=false 2>&1 )
}

# Jest prints the per-test ✓/✕ tree ONLY when a single spec matches; with two paths it prints just
# the ● failure bullets and the summary. A proof that counted ✕ lines would have called every one of
# these mutations GREEN. The verdict is read off the summary line, and the summary line being ABSENT
# (a suite that failed to load at all) is itself a failure rather than a pass.
tally  () { grep -Eo 'Tests: +[0-9]+ (failed|passed)' <<<"$1" | tr '\n' ' '; }
failed () { grep -qE 'Tests:.*[0-9]+ failed' <<<"$1"; }
ran    () { grep -qE '^Tests: ' <<<"$1"; }
bullets () { grep -E '^  ● ' <<<"$1" | sed 's/^/      /'; }

RESULT="$SCRATCH/mutation-proof.txt"
: > "$RESULT"
say () { echo "$*" | tee -a "$RESULT"; }

say "L-XZ-RESIDUAL-SITES mutation proof"
say "generated by lanes/L-XZ-RESIDUAL-SITES/mutation-proof.sh"
say ""

# ---------------------------------------------------------------------------------------------
# A. The new tests against the UNPORTED baseline.
# ---------------------------------------------------------------------------------------------
say "=== A. new tests vs UNPORTED baseline b150668b ==="
BASE="$SCRATCH/baseline"
mkdir -p "$BASE"
( cd "$LANE_ROOT" && git archive b150668b ) | ( cd "$BASE" && tar -xf - )
cp "$LANE_ROOT/test/xz-residual-sites.test.js" "$BASE/test/"
cp "$LANE_ROOT/test/xz-negated-absence.test.js" "$BASE/test/"
# `git archive` materialises the `core` GITLINK as an empty directory, so a bare `ln -s` would drop
# the link INSIDE it and the export would resolve no core module at all.
rm -rf "$BASE/core"
ln -s "$SHARED_MODULES" "$BASE/node_modules"
ln -s "$LANE_ROOT/core" "$BASE/core"
OUT="$(run "$BASE")"
if failed "$OUT"; then
  say "  RED as required: $(tally "$OUT")"
else
  say "  *** THE NEW TESTS PASS ON THE UNPORTED BASELINE — they prove nothing ***  $(tally "$OUT")"
fi
say "  assertions that fail without the port:"
say "$(bullets "$OUT")"
say "  what the unported receipt row actually rendered:"
say "$(grep -m2 -E 'Received string:' <<<"$OUT" | sed 's/^/      /')"
say ""

# ---------------------------------------------------------------------------------------------
# The ported tree, unmutated. Must be green.
# ---------------------------------------------------------------------------------------------
say "=== B0. ported tree, unmutated ==="
PORTED="$SCRATCH/ported"
export_tree "$PORTED"
OUT="$(run "$PORTED")"
if ran "$OUT" && ! failed "$OUT"; then
  say "  GREEN: $(tally "$OUT")"
else
  say "  *** NOT GREEN — every mutation below is meaningless ***  $(tally "$OUT")"
fi
say ""

# ---------------------------------------------------------------------------------------------
# B. Mutations. Each is applied to a fresh export.
# ---------------------------------------------------------------------------------------------
mutate () {  # mutate <label> <file> <sed-expr>
  local label="$1" file="$2" expr="$3"
  local dir="$SCRATCH/m$(echo "$label" | tr -cd 'a-zA-Z0-9')"
  export_tree "$dir"
  perl -0777 -i -pe "$expr" "$dir/$file"
  if cmp -s "$dir/$file" "$PORTED/$file"; then
    say "  [$label] MUTATION DID NOT APPLY — proof is vacuous"
    return
  fi
  local out; out="$(run "$dir")"
  if failed "$out"; then
    say "  [$label] RED — $(tally "$out")"
    say "$(bullets "$out" | head -4)"
  elif ! ran "$out"; then
    say "  [$label] RED — the suite could not even load"
    say "$(grep -m1 -A2 'failed to run' <<<"$out" | sed 's/^/      /')"
  else
    say "  [$label] *** GREEN — NOT CAUGHT ***"
  fi
}

say "=== B. mutations of this lane's change ==="

mutate "M1 receipt row reverts to the literal sign" \
  components/admin/pos/PosReceiptView.vue \
  's/\{\{ negatedPriceLabel\(line\.discountAmount\) \}\}/−{{ priceLabel(line.discountAmount) }}/'

mutate "M2 check line reverts to the literal sign" \
  components/admin/pos/CheckLine.vue \
  's/\{\{ negatedPriceLabel\(group\.discountAmount\) \}\}/−{{ priceLabel(group.discountAmount) }}/'

mutate "M3 check panel total reverts to the literal sign" \
  components/admin/pos/CheckPanel.vue \
  's/\{\{ negatedPriceLabel\(totalDiscount\) \}\}/−{{ priceLabel(totalDiscount) }}/'

mutate "M4 the tempting wrong fix: delete the sign, keep the formatter" \
  components/admin/pos/PosReceiptView.vue \
  's/\{\{ negatedPriceLabel\(line\.discountAmount\) \}\}/{{ priceLabel(line.discountAmount) }}/'

mutate "M5 the sign is re-owned by the caller instead of the label" \
  components/admin/pos/CheckLine.vue \
  's/return negatedAmountLabel\(amountMinor, this\.priceLabel\);/return MINUS_SIGN + this.priceLabel(amountMinor);/; s/import \{ negatedAmountLabel \}/import { negatedAmountLabel, MINUS_SIGN }/'

mutate "M6 the formatter is handed the negated value, not the magnitude" \
  components/admin/pos/CheckPanel.vue \
  's/return negatedAmountLabel\(amountMinor, this\.priceLabel\);/return isAmountStated(amountMinor) ? this.priceLabel(-Number(amountMinor)) : UNKNOWN_AMOUNT;/; s/import \{ negatedAmountLabel \}/import { negatedAmountLabel, isAmountStated, UNKNOWN_AMOUNT }/'

mutate "M7 tripwire slices at the FIRST closing tag, not the root one" \
  test/xz-negated-absence.test.js \
  's/source\.lastIndexOf\(.<\/template>.\)/source.indexOf("<\/template>")/'

mutate "M8 tripwire scans a directory that does not exist" \
  test/xz-negated-absence.test.js \
  "s{'\.\./components/admin/pos'}{'../components/admin/pos-nope'}"

mutate "M9 tripwire narrows back to the one file the defect was found in" \
  test/xz-negated-absence.test.js \
  "s/\.filter\(f => f\.endsWith\('\.vue'\)\)/.filter(f => f === 'XReportView.vue')/"

say ""
say "full output: $RESULT"
cp "$RESULT" "$LANE_ROOT/lanes/L-XZ-RESIDUAL-SITES/mutation-proof.txt"
