export enum ActionName {
    Load = 'load',
    SetCurrentUser = 'setCurrentUser',
    SetCurrentStore = 'setCurrentStore',
    GetOrders = 'GetOrders',
    GetStoreProducts = 'GetStoreProducts',
    ClearState = 'clearState',
    SetNotificationId = 'SetNotificationId',
    SetNotificationApproved = 'SetNotificationApproved',
    FileUploadEvent = 'FileUploadEvent',
    ClearFileUploadEvent = 'ClearFileUploadEvent',
    SetProductsQuery = 'SetProductsQuery',
    UpdateCartInDbAndSetState = 'UpdateCartInDbAndSetState',
    SetDeliveryAddress = 'SetDeliveryAddress',
    GetStores = 'GetStores',
    GetStore = 'GetStore',
    RemoveCart = 'RemoveCart',
    SetLineItem = 'SetLineItem',
    SetCartRootProperties = 'SetCartRootProperties',
    RemoveLineItem = 'RemoveLineItem'
}