export enum MutationName {
    Load = 'load',
    SetCurrentUser = 'setCurrentUser',
    SetCurrentStore = 'setCurrentStore',
    SetOrders = 'SetOrders',
    SetStoreProducts = 'SetStoreProducts',
    ClearCurrentUserAndStore = 'clearCurrentUserAndStore',
    SetNotificationId = 'SetNotificationId',
    SetNotificationApproved = 'SetNotificationApproved',
    FileUploadEvent = 'FileUploadEvent',
    ClearFileUploadEvent = 'ClearFileUploadEvent',
    SetProductsQuery = 'SetProductsQuery',
    StartNewOrderNotificationsInterval = 'StartNewOrderNotificationsInterval',
    StopNewOrderNotificationsInterval = 'StopNewOrderNotificationsInterval',
    SetDeliveryAddress = 'SetDeliveryAddress',
    ClearCurrentUser = 'ClearCurrentUser',
    SetCarts = 'SetCarts',
    SetStores = 'SetStores',
    SetStore = 'SetStore',
    RemoveCart = 'RemoveCart',
    SetCartIsLoading = 'SetCartIsLoading',
    SetLineItem = 'SetLineItem',
    SetCartRootProperties = 'SetCartRootProperties',
    RemoveLineItem = 'RemoveLineItem'
}