#!/usr/bin/env bash
# Mutation proof for L-CHECK-LINEAMOUNT-UNGATED-SUM.
#
# IN A SCRATCH EXPORT, NEVER IN PLACE — the convention this lane inherits from
# `lanes/L-XZ-RESIDUAL-SITES/mutation-proof.sh`. Five lanes have been live in these files tonight;
# every mutation below happens inside a throwaway copy under $SCRATCH and the tree this script is
# run from is never written to.
#
# TWO KINDS OF PROOF:
#   A. BEFORE/AFTER. The new test is run against the UNPORTED baseline (7a72c02). It must FAIL there,
#      printing the refund the old sum actually built. A test that passes on the code it claims to
#      fix proves nothing.
#   B. MUTATIONS. Each is a plausible wrong version of this lane's change. Every one must go red, and
#      the run records WHICH assertion caught it. M3 is the one the brief names: the fix that gates
#      both sums and still builds a return out of them.
#
# Usage:  bash lanes/L-CHECK-LINEAMOUNT-UNGATED-SUM/mutation-proof.sh
set -u

LANE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRATCH="${SCRATCH:-/private/tmp/claude-501/-Users-svendaneel-okam/766072d3-8965-4c45-be67-76b407d86aaf/scratchpad}/check-lineamount-mut"
SHARED_MODULES="/Users/svendaneel/okam/Web-modules/node_modules"
SPEC="test/check-lineamount-sum.test.js"
BASELINE="7a72c02"

rm -rf "$SCRATCH"; mkdir -p "$SCRATCH"

export_tree () {
  local dest="$1"
  mkdir -p "$dest"
  ( cd "$LANE_ROOT" && tar --exclude=./.git --exclude=./node_modules --exclude=./core \
      --exclude=./.nuxt --exclude=./dist -cf - . ) | ( cd "$dest" && tar -xf - )
  ln -s "$SHARED_MODULES" "$dest/node_modules"
  ln -s "$LANE_ROOT/core" "$dest/core"
}

run () { ( cd "$1" && npx jest $SPEC --coverage=false 2>&1 ); }

# The verdict is read off the summary line. A suite that failed to LOAD prints no summary at all, and
# that is a failure rather than a pass — a proof that counted only ✕ lines would call it green.
tally   () { grep -Eo 'Tests: +[0-9]+ (failed|passed)' <<<"$1" | tr '\n' ' '; }
failed  () { grep -qE 'Tests:.*[0-9]+ failed' <<<"$1"; }
ran     () { grep -qE '^Tests: ' <<<"$1"; }
bullets () { grep -E '^  ● ' <<<"$1" | sed 's/^/      /'; }

RESULT="$SCRATCH/mutation-proof.txt"
: > "$RESULT"
say () { echo "$*" | tee -a "$RESULT"; }

say "L-CHECK-LINEAMOUNT-UNGATED-SUM mutation proof"
say "generated by lanes/L-CHECK-LINEAMOUNT-UNGATED-SUM/mutation-proof.sh"
say ""

# ---------------------------------------------------------------------------------------------
# A. The new test against the UNPORTED baseline.
# ---------------------------------------------------------------------------------------------
say "=== A. new test vs UNPORTED baseline $BASELINE ==="
BASE="$SCRATCH/baseline"
mkdir -p "$BASE"
( cd "$LANE_ROOT" && git archive "$BASELINE" ) | ( cd "$BASE" && tar -xf - )
cp "$LANE_ROOT/$SPEC" "$BASE/test/"
# `git archive` materialises the `core` GITLINK as an empty directory, so a bare `ln -s` would drop
# the link INSIDE it and the export would resolve no core module at all.
rm -rf "$BASE/core"
ln -s "$SHARED_MODULES" "$BASE/node_modules"
ln -s "$LANE_ROOT/core" "$BASE/core"
OUT="$(run "$BASE")"
if failed "$OUT"; then
  say "  RED as required: $(tally "$OUT")"
else
  say "  *** THE NEW TEST PASSES ON THE UNPORTED BASELINE — it proves nothing ***  $(tally "$OUT")"
fi
say "  assertions that fail without this lane:"
say "$(bullets "$OUT")"
say "  the refund the old sum actually built (absent world vs zero world):"
say "$(grep -m6 -E 'Expected|Received|expect\(' <<<"$OUT" | sed 's/^/      /')"
say ""

# ---------------------------------------------------------------------------------------------
# B0. The ported tree, unmutated. Must be green or every mutation below is meaningless.
# ---------------------------------------------------------------------------------------------
say "=== B0. ported tree, unmutated ==="
PORTED="$SCRATCH/ported"
export_tree "$PORTED"
OUT="$(run "$PORTED")"
if ran "$OUT" && ! failed "$OUT"; then
  say "  GREEN: $(tally "$OUT")"
else
  say "  *** NOT GREEN — every mutation below is meaningless ***  $(tally "$OUT")"
fi
say ""

# ---------------------------------------------------------------------------------------------
# B. Mutations.
# ---------------------------------------------------------------------------------------------
mutate () {  # mutate <label> <file> <perl-expr>
  local label="$1" file="$2" expr="$3"
  local dir="$SCRATCH/m$(echo "$label" | tr -cd 'a-zA-Z0-9')"
  export_tree "$dir"
  perl -0777 -i -pe "$expr" "$dir/$file"
  if cmp -s "$dir/$file" "$PORTED/$file"; then
    say "  [$label] MUTATION DID NOT APPLY — proof is vacuous"
    return
  fi
  local out; out="$(run "$dir")"
  if failed "$out"; then
    say "  [$label] RED — $(tally "$out")"
    say "$(bullets "$out" | head -4)"
  elif ! ran "$out"; then
    say "  [$label] RED — the suite could not even load"
    say "$(grep -m1 -A2 'failed to run' <<<"$out" | sed 's/^/      /')"
  else
    say "  [$label] *** GREEN — NOT CAUGHT ***"
  fi
}

say "=== B. mutations of this lane's change ==="

mutate "M1 the line sum reverts to the ungated +=" \
  components/admin/pos/CheckPanel.vue \
  's/g\.lineAmount = statedSum\(g\.lineAmount, line\.netLineAmount\);/g.lineAmount += line.netLineAmount;/'

mutate "M2 the deposit sum reverts to the || 0 coercion" \
  components/admin/pos/CheckPanel.vue \
  's/g\.depositAmount = statedSum\(g\.depositAmount, line\.depositAmount\);/g.depositAmount += line.depositAmount || 0;/'

# THE ONE THE BRIEF NAMES. Both sums stay gated; the refund is built from them anyway. This is the
# fix a sum-only test would have accepted, and it settles `null * 1` as a silent kr 0,00.
mutate "M3 THE SUM-ONLY FIX: both sums gated, refusal deleted" \
  components/admin/pos/SellScreen.vue \
  's/      const unpriceable = groups\.filter.*?\n      \}\n//s'

mutate "M4 the deposit tag reverts to > 0 (the silent switch-off)" \
  components/admin/pos/CheckLine.vue \
  's/return isAmountInPlay\(this\.group\.depositAmount\);/return this.group.depositAmount > 0;/'

# A truthiness guard where the absence rule belongs: `!0` is true, so the fully-comped bill — a
# stated zero, a real reading — is refused alongside the absent one and a legitimate return is blocked.
mutate "M5 the refusal uses truthiness instead of the absence rule" \
  components/admin/pos/SellScreen.vue \
  's/groups\.filter\(g => !isAmountStated\(g\.lineAmount\)\)/groups.filter(g => !g.lineAmount)/'

mutate "M6 the refusal inspects only the first row" \
  components/admin/pos/SellScreen.vue \
  's/groups\.filter\(g => !isAmountStated\(g\.lineAmount\)\)/groups.slice(0, 1).filter(g => !isAmountStated(g.lineAmount))/'

mutate "M7 isAmountInPlay loses its absence arm (back to > 0)" \
  utils/price.js \
  's/export function isAmountInPlay \(amountMinor\) \{\n  if \(!isAmountStated\(amountMinor\)\) \{ return true \}\n  return Number\(amountMinor\) > 0\n\}/export function isAmountInPlay (amountMinor) {\n  return Number(amountMinor) > 0\n}/s'

mutate "M8 isAmountInPlay renders for every stated amount (column widens)" \
  utils/price.js \
  's/export function isAmountInPlay \(amountMinor\) \{\n  if \(!isAmountStated\(amountMinor\)\) \{ return true \}\n  return Number\(amountMinor\) > 0\n\}/export function isAmountInPlay (amountMinor) {\n  return true\n}/s'

mutate "M9 statedSum on the line sum is not sticky (absence forgiven by later members)" \
  utils/price.js \
  's/    if \(!isAmountStated\(amount\)\) \{ return null \}\n    total \+= Number\(amount\)/    if (isAmountStated(amount)) { total += Number(amount) }/s'

say ""
say "full output: $RESULT"
cp "$RESULT" "$LANE_ROOT/lanes/L-CHECK-LINEAMOUNT-UNGATED-SUM/mutation-proof.txt"
