#!/usr/bin/env python3
"""Emit the script-derived appendix: every branch, its bucket, and the proof command."""
import json
an=json.load(open("data/analysis.json")); su=json.load(open("data/supersede.json"))
od=json.load(open("data/order.json")); cl=json.load(open("data/classified.json"))
L=[]
L.append("## Appendix A — full classification, every branch in both repositories\n")
L.append("Generated by `data/classify.py` -> `data/analyze.py` -> `data/supersede.py` -> `data/order.py`.")
L.append("Regenerate: `python3 data/classify.py && python3 data/analyze.py && python3 data/supersede.py "
         "&& python3 data/migrations.py && python3 data/order.py && python3 data/render.py`\n")
for key,repo in (("fe","Web-modules (frontend)"),("be","OkamAPI-modules (backend)")):
    tot=len(cl[key]["branches"])
    anc=[b for b,r in cl[key]["branches"].items() if r["bucket"]=="contained-ancestor"]
    L.append("\n### %s — %d refs\n"%(repo,tot))
    L.append("| bucket | n | proof |")
    L.append("|---|---:|---|")
    L.append("| contained (ancestor of tip; merge is a no-op) | %d | `git rev-list --left-right --count TIP...B` -> ahead=0 |"%len(anc))
    L.append("| contained by content only (tree equal, ref ahead) | 0 | `git merge-tree --write-tree TIP B` == `TIP^{tree}` |")
    L.append("| outstanding, live | %d | ahead>0, behind<150 |"%an[key]["n_live"])
    L.append("| outstanding, stale epoch | %d | ahead>0, behind>=300 |"%an[key]["n_stale"])
    L.append("| ...of live, superseded by another live branch | %d | `git merge-base --is-ancestor B C` |"%len(su[key]["superseded_by_ancestry"]))
    L.append("| ...of live, excluded by ruling | %d | see Cannot-compose |"%len(od[key]["excluded"]))
    L.append("| **mergeable heads** | **%d** | not superseded, alias-collapsed, not excluded |"%od[key]["n_heads"])
    L.append("\n**Contained (ancestor) — merge is a no-op, do not merge:**\n")
    L.append("`"+"`, `".join(sorted(anc))+"`\n" if anc else "(none)\n")
    if su[key]["superseded_by_ancestry"]:
        L.append("\n**Superseded — its content lands via the branch named; merging both lands it twice:**\n")
        L.append("| superseded branch | superseded by |")
        L.append("|---|---|")
        for b,v in sorted(su[key]["superseded_by_ancestry"].items()):
            L.append("| `%s` | %s |"%(b,", ".join("`%s`"%x for x in v)))
    if su[key]["alias_groups"]:
        L.append("\n**Alias groups — one commit under several refs (one unit of work, not several):**\n")
        for s,v in su[key]["alias_groups"].items():
            L.append("- `%s` = %s"%(s[:9],", ".join("`%s`"%x for x in sorted(v))))
    L.append("\n**Mergeable heads, in the proposed order:**\n")
    for t,lab in (("T1_migration","T1 — migration-bearing (C2 serialised set, deepest first)"),
                  ("T2_hub","T2 — touches a hub file (>=5 heads touch it)"),
                  ("T3_rest","T3 — other collisions"),
                  ("T4_independent","T4 — independent, degree 0, parallelisable")):
        hs=od[key][t]
        if not hs: continue
        L.append("\n*%s* (%d):\n"%(lab,len(hs)))
        for h in hs:
            d=od[key]["degree"].get(h,0)
            extra=" **+%d migrations**"%od[key]["T1_depth"][h] if t=="T1_migration" else ""
            L.append("- `%s` — collides with %d other head(s)%s"%(h,d,extra))
    L.append("\n**Hub files (the collision surface), by how many heads touch each:**\n")
    for p,n in list(od[key]["hub_touch"].items())[:14]:
        L.append("- `%s` — %d heads"%(p,n))
open("data/appendix.md","w").write("\n".join(L))
print("appendix written:",len("\n".join(L).split("\n")),"lines")
